### ISSUE TITLE
RETRO/SPIKE: More active involvement upstream

### ISSUE THREAD

**Issue by heyselbi** [red-hat-data-services/odh-model-controller#16]

**Comment by israel-hdez** [comment]
For this ticket, we only needed For this ticket, we only needed a list of the communities we are and want to be involved - under the domain of model serving.

Currently, the list of upstream communities we are and should be active collaborating in are the following:

* [KServe](https://github.com/kserve/) - For [KServe](https://github.com/kserve/kserve) and [ModelMesh](https://github.com/kserve/modelmesh-serving) projects.
  * This is the basic stack of model serving in ODH.
  * Indirectly, we may need to be involved on [Istio](https://istio.io/) and [KNative](https://knative.dev/docs/) communities. Perhaps, only as users (e.g. asking questions) and not as code contributors.
* [OpenVINO](http://github.com/openvinotoolkit) - Because of OVMS, which is the model server that is currently provided supported out of the box in OpenDataHub. Supported  model formats include Tensorflow, ONNX, PyTorch. It supports using Intel GPUs for inference, and also Intel CPUs.
* [Triton](http://github.com/triton-inference-server) - This is NVIDIA's Inference server. Some of the supported model formats are TensorRT, TensorFlow, PyTorch, ONNX, OpenVINO. It supports using NVidia GPUs for inference, and can also use x86 ARM CPUs.
* [Caikit](https://github.com/caikit) and [TGIS](https://github.com/IBM/text-generation-inference) - Since these seem to be a good choice for LLMs.
